spring:
  application:
    name: queue-edu
  rabbitmq:
    username: 'override-guest'
    password: 'override-password'

rabbit:
  properties:
    queueName: com.4rl1996.queue
    exchangeName: com.4rl1996.fanout
server:
  port: 8080
