spring:
  application:
    name: queue-edu
  rabbitmq:
    username: 'override-guest'
    password: 'override-password'

rabbit:
  properties:
    queueEduName: com.4rl1996.queue-edu-old-message
    routingKey: com.4rl1996.queue-edu-key
    queueEduNewName: com.4rl1996.queue-edu-new-message
    fanoutExchangeName: com.4rl1996.fanout
    directExchangeName: com.4rl1996.direct

server:
  port: 8080
